<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5fkMlaE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5fkMlaE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5fkMlaE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5fkMlaE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5fkMlaE\App_KernelDevDebugContainer([
    'container.build_hash' => '5fkMlaE',
    'container.build_id' => '62449a5f',
    'container.build_time' => 1668968858,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5fkMlaE');
