<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEwNeSu6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEwNeSu6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEwNeSu6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEwNeSu6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEwNeSu6\App_KernelDevDebugContainer([
    'container.build_hash' => 'EwNeSu6',
    'container.build_id' => '40a31e97',
    'container.build_time' => 1663229965,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEwNeSu6');
