<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXEjYWDk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEjYWDk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXEjYWDk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXEjYWDk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXEjYWDk\App_KernelDevDebugContainer([
    'container.build_hash' => 'XEjYWDk',
    'container.build_id' => 'ce376795',
    'container.build_time' => 1668616275,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXEjYWDk');
