<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'cottura_list' => [[], ['_controller' => 'App\\Controller\\CotturaController::listAction'], [], [['text', '/cottura/list']], [], [], []],
    'cottura_show' => [['id'], ['_controller' => 'App\\Controller\\CotturaController::showAction'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/cottura']], [], [], []],
    'app_cottura_new' => [[], ['_controller' => 'App\\Controller\\CotturaController::new'], [], [['text', '/cottura/new']], [], [], []],
    'cottura_edit' => [['id'], ['_controller' => 'App\\Controller\\CotturaController::edit'], ['id' => '\\d+'], [['text', '/edit'], ['variable', '/', '\\d+', 'id', true], ['text', '/cottura']], [], [], []],
    'app_cottura_delete' => [['id'], ['_controller' => 'App\\Controller\\CotturaController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cottura']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\PastaController::indexAction'], [], [['text', '/pasta/']], [], [], []],
    'pasta_list' => [[], ['_controller' => 'App\\Controller\\PastaController::listAction'], [], [['text', '/pasta/list']], [], [], []],
    'pasta_show' => [['id'], ['_controller' => 'App\\Controller\\PastaController::showAction'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/pasta']], [], [], []],
    'app_pasta_new' => [[], ['_controller' => 'App\\Controller\\PastaController::new'], [], [['text', '/pasta/new']], [], [], []],
    'pasta_edit' => [['id'], ['_controller' => 'App\\Controller\\PastaController::edit'], ['id' => '\\d+'], [['text', '/edit'], ['variable', '/', '\\d+', 'id', true], ['text', '/pasta']], [], [], []],
    'app_pasta_delete' => [['id'], ['_controller' => 'App\\Controller\\PastaController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/pasta']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
